version: '3.9'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    extra_hosts:
      #- host.docker.internal:host-gateway
      # sacar con ipconfig el inet
      - localhost:172.20.10.3
      - or-vitualhost.local:172.20.10.3
